### ISSUE TITLE
snacks section not currectly responding

### ISSUE THREAD

**Issue by pushkarroy** [Brijesh1963/Multipurpose-Website#8]
**Describe the bug*
snacks section of the navbar is not responding properly.
Like, if someone clicks on cookies it is navigating to the namkeen section.
The namkeen and sauces button is not responding.
if someone clicks on namkeen it navigates to the sauces section.

**To Reproduce**
1. Go to 'Snacks navbar'
2. Click on 'any of the potion'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Brijesh1963** [comment]
You are assign for this task...
